[tool.poetry]
name = "depgraph"
version = "0.1.0"
description = "Universal dependency graph builder for popular languages (MVP: Python + JS)"
authors = ["Твоё Имя <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "depgraph" }
]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
depgraph = "depgraph.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
