[tool.poetry]
name = "depgraph"
version = "0.1.0"
description = "Universal dependency graph builder for popular languages (MVP: Python + JS)"
authors = ["Твоё Имя <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "depgraph" }
]

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.16.0"
networkx = "^3.2.1"
pydot = "^2.0.0"
rich = "^14.1.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
ruff = "^0.5.7"

[tool.poetry.scripts]
depgraph = "depgraph.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
